name: Deploy vue_liquid_glass to Pages

permissions:
  contents: write     # 只需要往仓库里推 docs/ 目录

on:
  push:
    branches: [ main ]
    paths:
      - 'archive/vue_liquid_glass/**'
      - '.github/workflows/workflow.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: archive/vue_liquid_glass   # 只在子目录里操作

    steps:
      # 1) 拉代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Node 环境
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: archive/vue_liquid_glass/package-lock.json

      # 3) 安装依赖并构建
      - run: npm ci
      - run: npm run build

      # 4) 把 dist 产物移动到 docs/
      - name: Move build to docs
        run: |
          rm -rf ../../docs          # 删除旧的 docs/
          mv dist ../../docs         # 把新的 dist 变成 docs
          touch ../../docs/.nojekyll # 关掉 Jekyll 处理

      # 5) 提交到 main（docs 目录有变化时才推）
      - name: Commit & push if docs changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ../..
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          if git diff --cached --quiet; then
            echo "No docs changes."
          else
            git commit -m "ci: update Pages docs [skip ci]"
            git push origin main
          fi
