name: Deploy vue_liquid_glass to Pages

# ★ 给 GITHUB_TOKEN 写权限，才能 push 回 main
permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'archive/vue_liquid_glass/**'
      - '.github/workflows/workflow.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: archive/vue_liquid_glass

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}   # ★

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: archive/vue_liquid_glass/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Copy shader workers to public/assets
        run: |
          mkdir -p public/assets
          cp node_modules/@wxperia/liquid-glass-vue/dist/assets/*.js public/assets/ || true

      - name: Build project
        run: npm run build

      - name: Replace source with build output
        run: |
          rm -rf assets index.html
          cp -r dist/* .
          rm -rf dist
          touch .nojekyll

      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: auto-deploy vue_liquid_glass [skip ci]"
            git push origin main
          fi
