name: Deploy vue_liquid_glass to Pages

on:
  # ❶ 只有 main 分支且修改了 vue_liquid_glass 目录时触发
  push:
    branches: [ main ]
    paths:
      - 'archive/vue_liquid_glass/**'
  # ❷ 允许手动触发
  workflow_dispatch:

jobs:
  build-and-deploy:
    # 防止机器人自己的 commit 再次触发
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    # 所有 shell 命令默认在子目录执行
    defaults:
      run:
        working-directory: archive/vue_liquid_glass

    steps:
      # 1. 克隆仓库
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # 能推回 main

      # 2. Node 环境 + 依赖缓存
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: archive/vue_liquid_glass/package-lock.json

      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 4. 复制缺失的 shader-worker 到 public/assets
      - name: Copy shader workers to public/assets
        run: |
          mkdir -p public/assets
          cp node_modules/@wxperia/liquid-glass-vue/dist/assets/*.js public/assets/ || true

      # 5. 构建
      - name: Build project
        run: npm run build

      # 6. 用构建产物覆盖源码目录（仅子目录）
      - name: Replace source with build output
        run: |
          rm -rf assets index.html          # 清旧文件
          cp -r dist/* .                    # 平铺新文件
          rm -rf dist                       # 删除 dist
          touch .nojekyll                   # 禁用 Jekyll

      # 7. 提交并推回 main（如果有改动）
      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: auto-deploy vue_liquid_glass [skip ci]"
            git push origin main
          fi
